// tea-manage/src/components/layout/ThemeSettings.vue
<!--
  @file 主题设置抽屉
  @description 茶易管 v0.4.0 - 外观/排版/布局/辅助 4 组配置
-->
<template>
  <n-drawer
    :show="settingsOpen"
    :width="340"
    placement="right"
    @update:show="handleShowChange"
  >
    <n-drawer-content title="主题设置" closable>
      <!-- ============ 外观 ============ -->
      <div class="tea-settings-section">
        <div class="tea-settings-section-title">外观</div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">主题模式</span>
          <n-radio-group
            :value="themeMode"
            size="small"
            @update:value="setThemeMode"
          >
            <n-radio-button value="light">浅色</n-radio-button>
            <n-radio-button value="dark">深色</n-radio-button>
          </n-radio-group>
        </div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">主色调</span>
          <div class="tea-color-picker">
            <div
              v-for="c in colorOptions"
              :key="c.value"
              class="tea-color-dot"
              :class="{ 'tea-color-dot-active': settings.primary === c.value }"
              :style="{ background: c.hex }"
              :title="c.label"
              @click="updateSettings({ primary: c.value })"
            >
              <i v-if="settings.primary === c.value" class="i-mdi-check tea-settings-check" />
            </div>
          </div>
        </div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">侧栏风格</span>
          <n-radio-group
            :value="settings.sidebarStyle"
            size="small"
            @update:value="(v) => updateSettings({ sidebarStyle: v })"
          >
            <n-radio-button value="dark">深色</n-radio-button>
            <n-radio-button value="light">浅色</n-radio-button>
          </n-radio-group>
        </div>
      </div>

      <n-divider style="margin: 16px 0 12px;" />

      <!-- ============ 排版 ============ -->
      <div class="tea-settings-section">
        <div class="tea-settings-section-title">排版</div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">字号</span>
          <n-radio-group
            :value="settings.fontSize"
            size="small"
            @update:value="(v) => updateSettings({ fontSize: v })"
          >
            <n-radio-button value="small">小</n-radio-button>
            <n-radio-button value="standard">标准</n-radio-button>
            <n-radio-button value="large">大</n-radio-button>
          </n-radio-group>
        </div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">圆角</span>
          <n-radio-group
            :value="settings.radius"
            size="small"
            @update:value="(v) => updateSettings({ radius: v })"
          >
            <n-radio-button value="sharp">锐利</n-radio-button>
            <n-radio-button value="rounded">圆润</n-radio-button>
            <n-radio-button value="full">饱满</n-radio-button>
          </n-radio-group>
        </div>
      </div>

      <n-divider style="margin: 16px 0 12px;" />

      <!-- ============ 布局 ============ -->
      <div class="tea-settings-section">
        <div class="tea-settings-section-title">布局</div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">密度</span>
          <n-radio-group
            :value="settings.density"
            size="small"
            @update:value="(v) => updateSettings({ density: v })"
          >
            <n-radio-button value="comfortable">舒适</n-radio-button>
            <n-radio-button value="compact">紧凑</n-radio-button>
          </n-radio-group>
        </div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">侧栏宽度</span>
          <n-radio-group
            :value="settings.siderWidth"
            size="small"
            @update:value="(v) => updateSettings({ siderWidth: v })"
          >
            <n-radio-button :value="180">紧凑</n-radio-button>
            <n-radio-button :value="220">标准</n-radio-button>
            <n-radio-button :value="240">宽敞</n-radio-button>
          </n-radio-group>
        </div>
      </div>

      <n-divider style="margin: 16px 0 12px;" />

      <!-- ============ 辅助 ============ -->
      <div class="tea-settings-section">
        <div class="tea-settings-section-title">辅助</div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">护眼模式</span>
          <n-radio-group
            :value="settings.eyeCare"
            size="small"
            @update:value="(v) => updateSettings({ eyeCare: v })"
          >
            <n-radio-button value="off">关</n-radio-button>
            <n-radio-button value="mild">轻</n-radio-button>
            <n-radio-button value="moderate">中</n-radio-button>
            <n-radio-button value="strong">强</n-radio-button>
          </n-radio-group>
        </div>

        <div class="tea-settings-row">
          <span class="tea-settings-label">暖色温</span>
          <n-switch
            :value="settings.warmTone"
            size="small"
            @update:value="(v) => updateSettings({ warmTone: v })"
          />
        </div>
      </div>

      <n-divider style="margin: 16px 0 12px;" />

      <div style="display: flex; gap: 8px;">
        <n-button size="small" @click="handleReset">恢复默认</n-button>
      </div>

      <div style="margin-top: 16px; padding: 12px; background: var(--tea-primary-bg); border-radius: var(--tea-radius-md); font-size: 12px; color: var(--tea-text-secondary); line-height: 1.6;">
        💡 设置自动保存到本地，刷新页面后保留。
      </div>
    </n-drawer-content>
  </n-drawer>
</template>

<script setup lang="ts">
/**
 * ThemeSettings 组件逻辑
 * - 直接绑定 useThemeStore
 * - 实时写入，实时生效
 * - 关闭抽屉通过 store
 */
import { computed } from 'vue'
import { NDrawer, NDrawerContent, NRadioGroup, NRadioButton, NSwitch, NButton, NDivider } from 'naive-ui'
import { useThemeStore, type PrimaryColor } from '@/stores/theme'

const themeStore = useThemeStore()

const settingsOpen = computed(() => themeStore.settingsOpen)
const themeMode = computed(() => themeStore.themeMode)
const settings = computed(() => themeStore.settings)
const setThemeMode = (mode: 'light' | 'dark') => themeStore.setThemeMode(mode)
const updateSettings = (partial: any) => themeStore.updateSettings(partial)

function handleShowChange(show: boolean) {
  if (!show) themeStore.closeSettings()
}

function handleReset() {
  themeStore.resetSettings()
  // 主题模式不重置（用户偏好）
}

/** 主色选项 */
const colorOptions: { value: PrimaryColor; label: string; hex: string }[] = [
  { value: 'gold', label: '茶金', hex: '#4A6741' },
  { value: 'bamboo', label: '竹青', hex: '#5B8C5A' },
  { value: 'cinnabar', label: '朱砂', hex: '#B5483F' },
]
</script>

<style scoped>
.tea-settings-section {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.tea-settings-section-title {
  font-size: 13px;
  font-weight: 600;
  color: var(--tea-text-primary);
  margin-bottom: 4px;
}

.tea-settings-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.tea-settings-row-block {
  align-items: flex-start;
  flex-direction: column;
  gap: 8px;
}

.tea-settings-label {
  font-size: 12px;
  color: var(--tea-text-secondary);
  white-space: nowrap;
  flex-shrink: 0;
}

.tea-color-picker {
  display: flex;
  gap: 10px;
}

.tea-color-dot {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 2px solid transparent;
  transition: border-color var(--tea-transition-fast), transform var(--tea-transition-fast);
  flex-shrink: 0;
}

.tea-color-dot:hover {
  transform: scale(1.1);
}

.tea-color-dot-active {
  border-color: var(--tea-text-primary);
  box-shadow: 0 0 0 2px var(--tea-primary-supply);
}

.tea-settings-check {
  font-size: 14px;
  color: #fff;
}
</style>

// src/components/layout/ThemeSettings.tsx
/** @file 主题设置面板 - 外观/排版/布局/辅助配置，右侧抽屉 */
import { Drawer, Segmented, Switch, Input, Button, Divider } from 'antd'
import { useAppStore } from '../../stores/appStore'
import type { PrimaryColor, FontSize, SidebarWidth, NavMode, SidebarStyle, CompactMode, BorderRadiusStyle, EyeCareLevel } from '../../stores/appStore'

const COLOR_OPTIONS: { value: PrimaryColor; label: string; hex: string }[] = [
  { value: '#1677FF', label: '拂晓蓝', hex: '#1677FF' },
  { value: '#52C41A', label: '极光绿', hex: '#52C41A' },
  { value: '#722ED1', label: '酱紫', hex: '#722ED1' },
  { value: '#FA8C16', label: '日耀橙', hex: '#FA8C16' },
  { value: '#F5222D', label: '中国红', hex: '#F5222D' },
]

export default function ThemeSettings() {
  const { settingsOpen, setSettingsOpen, uiSettings, setUISettings, resetUISettings, themeMode, setThemeMode } = useAppStore()

  return (
    <Drawer
      title="主题设置"
      placement="right"
      width={340}
      open={settingsOpen}
      onClose={() => setSettingsOpen(false)}
      styles={{ body: { padding: '16px 20px' } }}
    >
      <SectionTitle>外观</SectionTitle>

      <SettingRow label="主题模式">
        <Segmented
          value={themeMode}
          onChange={(v) => setThemeMode(v as 'light' | 'dark')}
          size="small"
          options={[
            { label: '浅色', value: 'light' },
            { label: '深色', value: 'dark' },
          ]}
        />
      </SettingRow>

      {themeMode === 'light' && (
        <SettingRow label="侧边栏风格">
          <Segmented
            value={uiSettings.sidebarStyle}
            onChange={(v) => setUISettings({ sidebarStyle: v as SidebarStyle })}
            size="small"
            options={[
              { label: '深色', value: 'dark' },
              { label: '浅色', value: 'light' },
            ]}
          />
        </SettingRow>
      )}

      <div className="mb-5">
        <div className="text-[12px] mb-2" style={{ color: 'var(--gl-text-tertiary)' }}>主色调</div>
        <div className="flex gap-3 flex-wrap">
          {COLOR_OPTIONS.map((c) => (
            <div
              key={c.value}
              onClick={() => setUISettings({ primaryColor: c.value })}
              className="flex flex-col items-center gap-1 cursor-pointer"
            >
              <div
                className="w-8 h-8 rounded-full border-2 transition-all flex items-center justify-center"
                style={{
                  background: c.hex,
                  borderColor: uiSettings.primaryColor === c.value ? 'var(--gl-text-primary)' : 'transparent',
                  boxShadow: uiSettings.primaryColor === c.value ? `0 0 0 2px ${c.hex}40` : 'none',
                }}
              >
                {uiSettings.primaryColor === c.value && (
                  <span className="text-white text-[10px] font-bold">&#10003;</span>
                )}
              </div>
              <span className="text-[11px]" style={{ color: 'var(--gl-text-tertiary)' }}>{c.label}</span>
            </div>
          ))}
        </div>
      </div>

      <Divider style={{ margin: '8px 0 16px', borderColor: 'var(--gl-border-light)' }} />
      <SectionTitle>排版</SectionTitle>

      <SettingRow label="字号">
        <Segmented
          value={uiSettings.fontSize}
          onChange={(v) => setUISettings({ fontSize: v as FontSize })}
          size="small"
          options={[
            { label: '小', value: 'small' },
            { label: '标准', value: 'standard' },
            { label: '大', value: 'large' },
          ]}
        />
      </SettingRow>

      <SettingRow label="圆角风格">
        <Segmented
          value={uiSettings.borderRadius}
          onChange={(v) => setUISettings({ borderRadius: v as BorderRadiusStyle })}
          size="small"
          options={[
            { label: '锐利', value: 'sharp' },
            { label: '圆润', value: 'rounded' },
            { label: '饱满', value: 'full' },
          ]}
        />
      </SettingRow>

      <Divider style={{ margin: '8px 0 16px', borderColor: 'var(--gl-border-light)' }} />
      <SectionTitle>布局</SectionTitle>

      <SettingRow label="紧凑模式">
        <Segmented
          value={uiSettings.compactMode}
          onChange={(v) => setUISettings({ compactMode: v as CompactMode })}
          size="small"
          options={[
            { label: '舒适', value: 'comfortable' },
            { label: '紧凑', value: 'compact' },
          ]}
        />
      </SettingRow>

      <SettingRow label="侧边栏宽度">
        <Segmented
          value={uiSettings.sidebarWidth}
          onChange={(v) => setUISettings({ sidebarWidth: v as SidebarWidth })}
          size="small"
          options={[
            { label: '紧凑', value: 180 },
            { label: '标准', value: 220 },
            { label: '宽敞', value: 260 },
          ]}
        />
      </SettingRow>

      <SettingRow label="导航模式">
        <Segmented
          value={uiSettings.navMode}
          onChange={(v) => setUISettings({ navMode: v as NavMode })}
          size="small"
          options={[
            { label: '单展开', value: 'single' },
            { label: '全部展开', value: 'all' },
          ]}
        />
      </SettingRow>

      <Divider style={{ margin: '8px 0 16px', borderColor: 'var(--gl-border-light)' }} />
      <SectionTitle>辅助</SectionTitle>

      <SettingRow label="护眼模式">
        <Segmented
          value={uiSettings.eyeCare}
          onChange={(v) => setUISettings({ eyeCare: v as EyeCareLevel })}
          size="small"
          options={[
            { label: '关闭', value: 'off' },
            { label: '轻柔', value: 'mild' },
            { label: '适中', value: 'moderate' },
            { label: '强效', value: 'strong' },
          ]}
        />
      </SettingRow>

      <SettingRow label="色温偏暖">
        <Switch
          size="small"
          checked={uiSettings.warmTone}
          onChange={(checked) => setUISettings({ warmTone: checked })}
        />
      </SettingRow>

      <SettingRow label="搜索快捷键">
        <Input
          value={uiSettings.searchShortcut}
          onChange={(e) => setUISettings({ searchShortcut: e.target.value })}
          size="small"
          style={{ borderRadius: 'var(--gl-radius-md)', width: 120 }}
        />
      </SettingRow>
      <div className="text-[11px] mt-[-8px] mb-3" style={{ color: 'var(--gl-text-tertiary)' }}>
        快捷键功能开发中
      </div>

      <Divider style={{ margin: '12px 0 16px', borderColor: 'var(--gl-border-light)' }} />

      <div className="flex gap-2">
        <Button onClick={resetUISettings} size="small">恢复默认</Button>
      </div>
    </Drawer>
  )
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="text-[13px] font-semibold mb-3"
      style={{ color: 'var(--gl-text-primary)' }}
    >
      {children}
    </div>
  )
}

function SettingRow({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-center justify-between mb-4">
      <span className="text-[12px]" style={{ color: 'var(--gl-text-secondary)' }}>{label}</span>
      {children}
    </div>
  )
}
