// tea-manage/src/components/layout/TabBar.vue
<!--
  @file 多标签页栏
  @description v0.4.0 核心组件 - 浏览器式多任务标签
  @feature 开关/激活/双击关闭/右键菜单/拖拽排序/横向滚动+遮罩
-->
<template>
  <div class="tea-tab-bar">
    <!-- 左侧渐变遮罩 -->
    <div class="tea-mask-left" :class="{ 'tea-mask-visible': showLeftMask }" />

    <!-- 左滚动按钮 -->
    <div
      v-if="showLeftMask"
      class="tea-tab-bar-scroll-btn"
      @click="scrollBy(-200)"
    >
      <i class="i-mdi-chevron-left tea-tab-scroll-icon" />
    </div>

    <!-- 标签滚动容器 -->
    <div
      ref="scrollRef"
      class="tea-tab-bar-scroll"
      @wheel.passive="handleWheel"
      @scroll="checkOverflow"
    >
      <div
        v-for="(tab, idx) in tabs"
        :key="tab.key"
        class="tea-tab"
        :class="{
          'tea-tab-active': activeKey === tab.key,
          'tea-tab-drag-over': dragOverIndex === idx && dragIndex !== null && dragIndex !== idx,
        }"
        :style="{ opacity: dragIndex === idx ? 0.4 : 1 }"
        draggable="true"
        @click="handleClick(tab)"
        @auxclick.middle="handleMiddleClick(tab)"
        @dblclick="handleDoubleClick(tab)"
        @contextmenu.prevent="handleContextMenu($event, tab, idx)"
        @dragstart="handleDragStart($event, idx)"
        @dragover.prevent="handleDragOver($event, idx)"
        @drop.prevent="handleDrop($event, idx)"
        @dragend="handleDragEnd"
      >
        <span class="tea-tab-title">{{ tab.title }}</span>
        <span
          v-if="tab.closable"
          class="tea-tab-close"
          @click.stop="handleClose(tab)"
          title="关闭"
        >
          <i class="i-mdi-close tea-tab-close-icon" />
        </span>
      </div>
    </div>

    <!-- 右滚动按钮 -->
    <div
      v-if="showRightMask"
      class="tea-tab-bar-scroll-btn"
      @click="scrollBy(200)"
    >
      <i class="i-mdi-chevron-right tea-tab-scroll-icon" />
    </div>

    <!-- 右侧渐变遮罩 -->
    <div class="tea-mask-right" :class="{ 'tea-mask-visible': showRightMask }" />

    <!-- 右键菜单 -->
    <n-dropdown
      placement="bottom-start"
      trigger="manual"
      :x="contextMenu.x"
      :y="contextMenu.y"
      :options="contextMenuOptions"
      :show="contextMenu.show"
      @clickoutside="contextMenu.show = false"
      @select="handleContextMenuSelect"
    />
  </div>
</template>

<script setup lang="ts">
/**
 * TabBar 组件逻辑
 * - 通过 useTabsStore 读取/操作标签
 * - 点击 → 激活并跳转
 * - 关闭 → 标签 store.removeTab（store 内部已处理激活态切换）
 * - 拖拽 → store.moveTab
 * - 滚动 → DOM 原生 scrollBy
 */
import { ref, reactive, computed, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { useRouter } from 'vue-router'
import { NDropdown, type DropdownOption } from 'naive-ui'
import { useTabsStore, type Tab } from '@/stores/tabs'

const router = useRouter()
const tabsStore = useTabsStore()

const tabs = computed(() => tabsStore.tabs)
const activeKey = computed(() => tabsStore.activeKey)
const dragIndex = computed(() => tabsStore.dragIndex)
const dragOverIndex = computed(() => tabsStore.dragOverIndex)

// ========== 滚动溢出检测 ==========
const scrollRef = ref<HTMLElement | null>(null)
const showLeftMask = ref(false)
const showRightMask = ref(false)

/**
 * 检查标签栏是否溢出，更新左右遮罩和滚动按钮状态
 */
function checkOverflow() {
  const el = scrollRef.value
  if (!el) return
  const overflow = el.scrollWidth > el.clientWidth + 2
  if (!overflow) {
    showLeftMask.value = false
    showRightMask.value = false
    return
  }
  showLeftMask.value = el.scrollLeft > 2
  showRightMask.value = el.scrollLeft < el.scrollWidth - el.clientWidth - 2
}

/**
 * 横向滚动
 */
function scrollBy(dx: number) {
  const el = scrollRef.value
  if (!el) return
  el.scrollBy({ left: dx, behavior: 'smooth' })
}

/**
 * 鼠标滚轮转为横向滚动
 */
function handleWheel(e: WheelEvent) {
  const el = scrollRef.value
  if (!el) return
  if (e.deltaY === 0 && e.deltaX === 0) return
  // 仅在垂直滚动时转为横向
  if (Math.abs(e.deltaY) > Math.abs(e.deltaX)) {
    el.scrollBy({ left: e.deltaY, behavior: 'auto' })
  }
}

// ========== 标签操作 ==========

/**
 * 点击标签 → 激活并跳转
 */
function handleClick(tab: Tab) {
  if (activeKey.value === tab.key) return
  tabsStore.setActiveKey(tab.key)
  router.push(tab.key)
}

/**
 * 双击标签 → 关闭（首页除外，由 store 内部保护）
 */
function handleDoubleClick(tab: Tab) {
  tabsStore.removeTab(tab.key)
}

/**
 * 鼠标中键点击 → 关闭
 */
function handleMiddleClick(tab: Tab) {
  tabsStore.removeTab(tab.key)
}

/**
 * 关闭按钮点击
 */
function handleClose(tab: Tab) {
  tabsStore.removeTab(tab.key)
}

// ========== 拖拽 ==========

function handleDragStart(e: DragEvent, idx: number) {
  if (!e.dataTransfer) return
  tabsStore.setDragIndex(idx)
  e.dataTransfer.effectAllowed = 'move'
  // 必须 setData 才能在 Firefox 触发 dragover
  e.dataTransfer.setData('text/plain', String(idx))
}

function handleDragOver(e: DragEvent, idx: number) {
  if (!e.dataTransfer) return
  e.dataTransfer.dropEffect = 'move'
  if (dragOverIndex.value !== idx) {
    tabsStore.setDragOverIndex(idx)
  }
}

function handleDrop(_e: DragEvent, idx: number) {
  const from = tabsStore.dragIndex
  if (from !== null && from !== idx) {
    tabsStore.moveTab(from, idx)
  }
  tabsStore.setDragIndex(null)
  tabsStore.setDragOverIndex(null)
}

function handleDragEnd() {
  tabsStore.setDragIndex(null)
  tabsStore.setDragOverIndex(null)
}

// ========== 右键菜单 ==========
const contextMenu = reactive({
  show: false,
  x: 0,
  y: 0,
  tab: null as Tab | null,
  idx: -1,
})

const contextMenuOptions = computed<DropdownOption[]>(() => {
  const items: DropdownOption[] = []
  const tab = contextMenu.tab
  const idx = contextMenu.idx
  if (!tab) return items

  if (tab.closable) {
    items.push({ key: 'close', label: '关闭', icon: () => h('i', { class: 'i-mdi-close' }) })
  }
  if (tabs.value.length > 1) {
    items.push({ key: 'closeOthers', label: '关闭其他' })
    items.push({ key: 'closeAll', label: '关闭所有' })
  }
  if (idx > 0) {
    items.push({ key: 'closeLeft', label: '关闭左侧' })
  }
  if (idx < tabs.value.length - 1) {
    items.push({ key: 'closeRight', label: '关闭右侧' })
  }
  return items
})

function handleContextMenu(e: MouseEvent, tab: Tab, idx: number) {
  contextMenu.show = false
  contextMenu.tab = tab
  contextMenu.idx = idx
  contextMenu.x = e.clientX
  contextMenu.y = e.clientY
  nextTick(() => {
    contextMenu.show = true
  })
}

function handleContextMenuSelect(key: string | number) {
  const tab = contextMenu.tab
  if (!tab) return
  switch (key) {
    case 'close':
      tabsStore.removeTab(tab.key)
      break
    case 'closeOthers':
      tabsStore.closeOtherTabs(tab.key)
      break
    case 'closeAll':
      tabsStore.closeAllTabs()
      break
    case 'closeLeft':
      tabsStore.closeLeftTabs(tab.key)
      break
    case 'closeRight':
      tabsStore.closeRightTabs(tab.key)
      break
  }
  contextMenu.show = false
}

// ========== 生命周期 ==========

let resizeObserver: ResizeObserver | null = null

onMounted(() => {
  // 初始检测
  setTimeout(checkOverflow, 50)
  // 窗口 resize 时重检
  window.addEventListener('resize', checkOverflow)
  // 容器尺寸变化时重检
  if (scrollRef.value) {
    resizeObserver = new ResizeObserver(() => checkOverflow())
    resizeObserver.observe(scrollRef.value)
  }
})

onBeforeUnmount(() => {
  window.removeEventListener('resize', checkOverflow)
  resizeObserver?.disconnect()
})

// 引入 h 用于 n-icon 渲染
import { h } from 'vue'
</script>

<style scoped>
.tea-tab-bar {
  flex: 1;
  display: flex;
  align-items: center;
  height: 100%;
  min-width: 0;
  position: relative;
  overflow: hidden;
}

.tea-tab-bar-scroll {
  flex: 1;
  display: flex;
  align-items: center;
  height: 100%;
  overflow-x: auto;
  overflow-y: hidden;
  scrollbar-width: none;
  -ms-overflow-style: none;
  padding: 0 8px;
  gap: 4px;
}

.tea-tab-bar-scroll::-webkit-scrollbar {
  display: none;
}

.tea-tab-bar-scroll-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 100%;
  cursor: pointer;
  color: var(--tea-text-tertiary);
  flex-shrink: 0;
  transition: color var(--tea-transition-fast), background var(--tea-transition-fast);
  z-index: 6;
  border-radius: var(--tea-radius-sm);
}

.tea-tab-bar-scroll-btn:hover {
  color: var(--tea-primary);
  background: var(--tea-primary-supply);
}

.tea-tab-scroll-icon {
  font-size: 12px;
}

.tea-tab-close-icon {
  font-size: 10px;
}
</style>

// src/components/layout/titlebar/TabBar.tsx
/** @file 标签页栏 - 管理打开的标签页列表、关闭标签、右键菜单和拖拽排序 */
import { useRef, useState, useEffect, useCallback } from 'react'
import {
  LeftOutlined,
  RightOutlined,
  CloseOutlined,
} from '@ant-design/icons'
import { Dropdown, type MenuProps } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useTabStore } from '../../../stores/tabStore'

/** TabBar 组件属性 */
interface TabBarProps {
  /** 双击标题栏时的回调（用于双击标签页关闭） */
  onTitlebarDoubleClick: (e: React.MouseEvent) => void
}

export default function TabBar({ onTitlebarDoubleClick }: TabBarProps) {
  const { tabs, activeKey, removeTab, setActiveKey, closeOtherTabs, closeAllTabs, closeLeftTabs, closeRightTabs, moveTab } = useTabStore()
  const navigate = useNavigate()
  const tabsRef = useRef<HTMLDivElement>(null)
  const [showLeftMask, setShowLeftMask] = useState(false)
  const [showRightMask, setShowRightMask] = useState(false)
  const [dragIndex, setDragIndex] = useState<number | null>(null)
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null)
  const resizeTimer = useRef<ReturnType<typeof setTimeout>>()

  /** 检查标签页容器是否溢出，更新左右遮罩状态 */
  const checkOverflow = useCallback(() => {
    const el = tabsRef.current
    if (!el) return
    const overflow = el.scrollWidth > el.clientWidth
    setShowLeftMask(overflow && el.scrollLeft > 2)
    setShowRightMask(overflow && el.scrollLeft < el.scrollWidth - el.clientWidth - 2)
  }, [])

  useEffect(() => {
    checkOverflow()
    const handleResize = () => {
      clearTimeout(resizeTimer.current)
      resizeTimer.current = setTimeout(checkOverflow, 150)
    }
    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
      clearTimeout(resizeTimer.current)
    }
  }, [tabs, checkOverflow])

  /** 标签页左右滚动 */
  const handleTabScroll = (direction: 'left' | 'right') => {
    const el = tabsRef.current
    if (!el) return
    el.scrollBy({ left: direction === 'left' ? -200 : 200, behavior: 'smooth' })
    setTimeout(checkOverflow, 300)
  }

  /** 鼠标滚轮横向滚动 */
  const handleWheel = (e: React.WheelEvent) => {
    e.currentTarget.scrollBy({ left: e.deltaY, behavior: 'auto' })
    setTimeout(checkOverflow, 50)
  }

  /** 生成标签页右键菜单 */
  const getContextMenu = (tab: typeof tabs[0], idx: number): MenuProps => {
    const items: MenuProps['items'] = []
    if (tab.closable !== false) {
      items.push({ key: 'close', label: '关闭', icon: <CloseOutlined /> })
    }
    if (tabs.length > 1) {
      items.push({ key: 'closeOthers', label: '关闭其他' })
      items.push({ key: 'closeAll', label: '关闭所有' })
    }
    if (idx > 0 && tabs.slice(0, idx).some((t) => t.closable !== false)) {
      items.push({ key: 'closeLeft', label: '关闭左边' })
    }
    if (idx < tabs.length - 1 && tabs.slice(idx + 1).some((t) => t.closable !== false)) {
      items.push({ key: 'closeRight', label: '关闭右边' })
    }
    return {
      items,
      onClick: ({ key }) => {
        switch (key) {
          case 'close': removeTab(tab.key); break
          case 'closeOthers': closeOtherTabs(tab.key); break
          case 'closeAll': closeAllTabs(); break
          case 'closeLeft': closeLeftTabs(tab.key); break
          case 'closeRight': closeRightTabs(tab.key); break
        }
      },
    }
  }

  const handleDragStart = (e: React.DragEvent, idx: number) => {
    setDragIndex(idx)
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.setData('text/plain', String(idx))
  }

  const handleDragOver = (e: React.DragEvent, idx: number) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = 'move'
    setDragOverIndex(idx)
  }

  const handleDrop = (e: React.DragEvent, idx: number) => {
    e.preventDefault()
    if (dragIndex !== null && dragIndex !== idx) {
      moveTab(dragIndex, idx)
    }
    setDragIndex(null)
    setDragOverIndex(null)
  }

  const handleDragEnd = () => {
    setDragIndex(null)
    setDragOverIndex(null)
  }

  return (
    <div
      data-tauri-drag-region
      className="flex-1 flex items-center relative h-full overflow-hidden"
      style={{ minWidth: 0 }}
      onDoubleClick={onTitlebarDoubleClick}
    >
      <div className={`gl-mask-left ${showLeftMask ? 'gl-mask-visible' : ''}`} />

      {showLeftMask && (
        <div
          className="gl-icon-btn flex-shrink-0 flex items-center justify-center cursor-pointer h-full rounded-sm transition-all z-10"
          style={{ width: 24, color: 'var(--gl-text-tertiary)' }}
          onClick={() => handleTabScroll('left')}
        >
          <LeftOutlined style={{ fontSize: 10 }} />
        </div>
      )}

      <div
        ref={tabsRef}
        data-tauri-drag-region
        className="flex items-center h-full overflow-hidden"
        style={{ scrollbarWidth: 'none', msOverflowStyle: 'none', flex: 1 }}
        onScroll={checkOverflow}
        onWheel={handleWheel}
      >
        {tabs.map((tab, idx) => {
          const isActive = activeKey === tab.key
          const isDragging = dragIndex === idx
          const isDragOver = dragOverIndex === idx
          return (
            <Dropdown
              key={tab.key}
              menu={getContextMenu(tab, idx)}
              trigger={['contextMenu']}
            >
              <div
                data-tab-key={tab.key}
                data-tab-closable={tab.closable !== false ? 'true' : 'false'}
                draggable
                onDragStart={(e) => handleDragStart(e, idx)}
                onDragOver={(e) => handleDragOver(e, idx)}
                onDrop={(e) => handleDrop(e, idx)}
                onDragEnd={handleDragEnd}
                onClick={() => { setActiveKey(tab.key); navigate(tab.key) }}
                className="flex items-center gap-1.5 h-8 px-3 cursor-pointer transition-all flex-shrink-0 text-[13px] relative select-none"
                style={{
                  maxWidth: 160,
                  color: isActive ? 'var(--gl-primary)' : 'var(--gl-text-secondary)',
                  fontWeight: isActive ? 600 : 400,
                  opacity: isDragging ? 0.4 : 1,
                  borderLeft: isDragOver && dragIndex !== null && dragIndex !== idx ? '2px solid var(--gl-primary)' : '2px solid transparent',
                  borderRadius: isActive ? 'var(--gl-radius-sm)' : 0,
                  background: isActive ? 'var(--gl-primary-supply)' : 'transparent',
                }}
              >
                <span className="truncate">{tab.title}</span>
                {tab.closable !== false && (
                  <span
                    onClick={(e) => { e.stopPropagation(); removeTab(tab.key) }}
                    className="gl-tab-close flex items-center justify-center w-4 h-4 rounded-full flex-shrink-0 transition-all"
                    style={{ color: 'var(--gl-text-tertiary)', fontSize: 10 }}
                  >
                    <CloseOutlined />
                  </span>
                )}
                {isActive && (
                  <div
                    className="absolute bottom-0 left-2 right-2 rounded-full"
                    style={{ height: 2, background: 'var(--gl-primary)', transition: 'all var(--gl-transition-fast)' }}
                  />
                )}
              </div>
            </Dropdown>
          )
        })}
      </div>

      {showRightMask && (
        <div
          className="gl-icon-btn flex-shrink-0 flex items-center justify-center cursor-pointer h-full rounded-sm transition-all z-10"
          style={{ width: 24, color: 'var(--gl-text-tertiary)' }}
          onClick={() => handleTabScroll('right')}
        >
          <RightOutlined style={{ fontSize: 10 }} />
        </div>
      )}

      <div className={`gl-mask-right ${showRightMask ? 'gl-mask-visible' : ''}`} />
    </div>
  )
}
